bindAddress: :53
debugHTTPAddress: 127.0.0.1:5555
dohEnabled: false
primaryDNS:
  - name: DNSPod-1
    address: 119.29.29.29:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: DNSPod-2
    address: 182.254.116.116:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
alternativeDNS:
  - name: Cloudflare-1
    address: 1.1.1.1:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Cloudflare-2
    address: 1.0.0.1:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Cloudflare-3
    address: 1.1.1.2:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Cloudflare-4
    address: 1.0.0.2:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Cloudflare-5
    address: 1.1.1.3:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
  - name: Cloudflare-6
    address: 1.0.0.3:53
    protocol: udp
    socks5Address:
    timeout: 6
    ednsClientSubnet:
      policy: disable
      externalIP:
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: false
whenPrimaryDNSAnswerNoneUse: primaryDNS
ipNetworkFile:
  primary: ../dns/overture/rules/ip-cn.txt
  alternative: ../dns/overture/rules/ip-non-cn.txt
domainFile:
  primary: ../dns/overture/rules/domain-cn.txt
  alternative: ../dns/overture/rules/domain-non-cn.txt
  matcher: full-map
hostsFile:
  hostsFile: ../dns/overture/rules/hosts.txt
  finder: full-map
minimumTTL: 0
domainTTLFile: ../dns/overture/rules/domain_ttl.txt
cacheSize: 0
cacheRedisUrl:
cacheRedisConnectionPoolSize:
rejectQType:
  - 255
